model:
  name: mobilenetv3_small_100
  checkpoint_path: models/best.pt
  image_size: 224

training:
  batch_size: 32
  epochs: 30
  learning_rate: 0.0003
  seed: 134

  pi_sample_weight_paper: 15.0
  pi_sample_weight_trash: 10.0
  trashnet_sample_weight: 1.0
inference:
  confidence_threshold: 0.35

data:  
  dir: data/raw  #Where the data actually lives 
  processed_dir: data/processed

hardware:
  gpio:
    ir_sensor_pin: 17
    servo_pin: 18
  servo:
    recycle_angle: 0
    waste_angle: 180

dry_run: true
